# Generated by Django 2.2.19 on 2022-05-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20220510_0749"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="tittle",
            new_name="title",
        ),
    ]
